"""empty message

Revision ID: 0629acb70ba5
Revises: 130458095691
Create Date: 2019-02-21 22:14:02.667410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0629acb70ba5'
down_revision = '130458095691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('confidence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'confidence')
    # ### end Alembic commands ###
